text_field:
  base: "block w-full border rounded-md py-2 px-3 focus:outline-none dark:bg-slate-700/40 dark:border-slate-500 dark:text-slate-300 dark:placeholder-slate-400 dark:focus:ring-slate-500 dark:focus:ring-2 dark:focus:border-transparent"
  valid: "border-slate-300 focus:ring-blue-600 focus:border-blue-600"
  invalid: "pr-10 border-red-300 text-red-900 placeholder-red-300 focus:ring-red-500 focus:border-red-500"
label:
  base: "block text-sm font-medium text-slate-700 dark:text-slate-200"
error_field:
  base: "mt-2 text-sm text-red-600 dark:text-red-500"
  visible: ""
  hidden: "hidden"
