inherit_from:
  - ../.rubocop.yml

Metrics/BlockLength:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/ExpectChange:
  EnforcedStyle: block

RSpec/MultipleExpectations:
  Max: 3
  Exclude:
    - 'system/**/*'

RSpec/DescribeClass:
  Exclude:
    - 'tasks/**/*'
